README.md

- Build Circle CI project
- Add badge to README
- Fails
See: #5

Feat: Add Circle CI badge to README

---

Gemfile
Gemfile.lock
Procfile
config/puma.rb

Added:
- Procfile
- puma.rb
- app.json

Heroku setup

---

README.md

- Add Circle CI Documentation to ReadME file.
See: #5

Feat: Circle CI Documentation

---

Gemfile
README.md
test/test_helper.rb

- Adds to Gemfile, ReadME, and tests
- Finishes Code Climate ticket.
See: #4

Feat: Integrate Code Climate and update Docs

---

Gemfile

restructure gemfile

---

Gemfile
README.md
test/test_helper.rb

@catheraaine 
Not sure why had changes to my gemfile.lock again...?

Modify gemfile

---

app/models/event.rb
test/unit/event_test.rb

Added additional tests for the event model and one validation. (I'm not sure if all names should be unique, but I still added it.
@boomingbrake @catheraaine @iAmNathanJ

Add additional tests for event model

---

README.md

@catheraaine @BC3209 @boomingbrake
README had some spelling and formatting errors on my part. I think this cleans it up. Let me know if anyone sees anything else. 😄

Chore: Update README.md - Cleanup

---

app/models/event.rb
test/models/event_test.rb

@catheraaine @iAmNathanJ @boomingbrake 
Additional tests for the event model. I might add two more and a couple of validations if we need them

Add additional model tests

---

config/secrets.yml

add secret_token from ENV["SECRET_TOKEN"]

Fix Heroku

---

config/initializers/secret_token.rb
config/secrets.yml

remove secret_token var from secrets.yml and add secret_token.rb

Fix Heroku Again

---

app/assets/stylesheets/events.scss
app/views/events/index.html.erb
app/views/layouts/application.html.erb

Adds styles for card, card title, and some fonts.

Feat: Card Markup: Titles

---

app/views/layouts/application.html.erb

This adds the lang attribute to the html tag, the viewport meta tag
to the head, conditionally loads html5shiv, and moves the application
js file to the bottom of the body.
@catheraaine @BC3209 @boomingbrake

Update application layout file:

---

app.json
app/controllers/application_controller.rb

@boomingbrake     
Added site-wide http auth to production app.
Need to check the review app to see how if that works.

:lock: Feat: Add basic http auth

---

app/assets/stylesheets/base/_global.scss
app/assets/stylesheets/base/_mixins.scss
app/assets/stylesheets/base/_variables.scss
app/assets/stylesheets/styles/_event-filters.scss
app/assets/stylesheets/styles/_events.scss
app/views/events/_event_list.html.erb
app/views/events/_location_icon.html.erb
app/views/events/_time_icon.html.erb

"Left" side of event card, static markup. 
- Does not close an issue, but allows @iAmNathanJ to access new styles. 
@BC3209 @boomingbrake

Feat: Static Markup "Left" Card (+ Styles)

---

app/assets/stylesheets/base/_global.scss
app/assets/stylesheets/styles/_events.scss
app/views/events/_event_list.html.erb
db/schema.rb

- Static Markup Only
- Buttons not included

Feat: Finish Card Front; Add Card Back - Static

---

app/assets/stylesheets/base/_colors.scss
app/assets/stylesheets/base/_global.scss
app/assets/stylesheets/main.scss
app/assets/stylesheets/styles/_event-filters.scss
app/assets/stylesheets/styles/_events.scss
app/assets/stylesheets/styles/_header.scss
app/assets/stylesheets/styles/_logo.scss

- Reconstruct `$gray` variables to add more depth and room for change.
- Replace variables where needed
- DRY up icon CSS
@iAmNathanJ @BC3209 @boomingbrake

:art: Refactor: Sassy Refactoring

---

app/models/event.rb
app/models/link.rb
db/migrate/20160517195647_create_links.rb
db/schema.rb
test/fixtures/links.yml
test/models/link_test.rb

Merge this please 
@BC3209 @iAmNathanJ @catheraaine

Add Link model. Association with Event defined.

---

app/assets/stylesheets/styles/_event-filters.scss
app/assets/stylesheets/styles/_forms.scss
app/views/events/_filters.html.erb

Marshal redesigned the filter checkboxes. This is the updated style. 
@catheraaine @BC3209 @boomingbrake Anyone want to review? 😄

New checkbox style

---

Gemfile
Gemfile.lock

Autoprefixing CSS! @BC3209 @boomingbrake @catheraaine Might need to merge the checkbox update before this one.

Add autoprefixer

---

app/assets/stylesheets/base/_buttons.scss
app/assets/stylesheets/styles/_events.scss
app/views/events/_event_list.html.erb

Full front and back of card with static styles!!! Let's close that issue! 
WOOO!
closes #43

Feat: Static Styling Card Back

---

app/assets/stylesheets/styles/_event-filters.scss
db/schema.rb

Iss 52 markup partial filter

---

app/views/events/_event_list.html.erb

- Links pull from Database 
closes #77

Feat: Dynamically display links

---

app/assets/stylesheets/styles/_events.scss

:bug: Fix: Remove Space between Cards

---

db/migrate/20160520145644_remove_column.rb
db/migrate/20160520145919_add_street_address_to_event.rb
db/migrate/20160520150001_add_city_to_event.rb
db/migrate/20160520150322_add_state_to_event.rb
db/migrate/20160520150354_add_zip_code_to_event.rb
db/schema.rb

I removed the location column and added street_address, city, state, and zip_code as new columns.
@catheraaine @iAmNathanJ @boomingbrake

Remove location field and add new attributes

---

app/views/layouts/_header.html

@iamnathanj @catheraaine @boomingbrake
I added the "mailto:" for the "submit" button and pre-populated the email subject and body

Add href email for submit button

---

app/assets/javascripts/01-shims.js
app/assets/javascripts/events.js
app/assets/stylesheets/styles/_event-filters.scss
app/assets/stylesheets/styles/_side-bar.scss

@boomingbrake @catheraaine @BC3209 
Needs review please. Thanks! 😄

No js hide filters

---

app/assets/javascripts/events.js
app/assets/stylesheets/base/_global.scss
app/assets/stylesheets/styles/_event-filters.scss
app/assets/stylesheets/styles/_header.scss
app/assets/stylesheets/styles/_logo.scss
app/assets/stylesheets/styles/_side-bar.scss
app/views/layouts/application.html.erb

@catheraaine Doing some more work on this. Will let you know when it's ready for review.

WIP Iss 80 ui cleanup

---

app/assets/stylesheets/styles/_side-bar.scss

@catheraaine I think this fixes a couple issues. Please try to break it!!!

refine ui drop down on mobile - kill bugs

---

app/controllers/events_controller.rb
app/views/events/show.html.erb

Also created event param variable.
@catheraaine @BC3209 @iAmNathanJ

Add show view for event detail view

---

app/assets/javascripts/events.js
app/assets/stylesheets/base/_global.scss
app/assets/stylesheets/styles/_side-bar.scss

@catheraaine @BC3209 @boomingbrake 
Try to break it!

MVP Stuff: contain full width site at 1440px

---

app/assets/stylesheets/styles/_events.scss

Feat: Truncate sharable links with "..."

---

app/assets/javascripts/events.js
app/assets/stylesheets/base/_global.scss
app/assets/stylesheets/base/_normalize.scss
app/assets/stylesheets/base/_reset.scss
app/assets/stylesheets/base/_variables.scss
app/assets/stylesheets/styles/_event-filters.scss
app/assets/stylesheets/styles/_events.scss
app/assets/stylesheets/styles/_logo.scss
app/assets/stylesheets/styles/_side-bar.scss

Because of feature requests for the UI, the sidebar and filters need to be re-worked. This is a WIP.

Fix mobile ui behavior

---

.byebug_history
Gemfile
Gemfile.lock
app/controllers/events_controller.rb
app/models/event.rb
app/views/events/_event_card.html.erb
app/views/events/_filters.html.erb
app/views/events/index.rss.builder
app/views/layouts/application.html.erb
db/migrate/20160526142409_acts_as_taggable_on_migration.acts_as_taggable_on_engine.rb
db/migrate/20160526142410_add_missing_unique_indices.acts_as_taggable_on_engine.rb
db/migrate/20160526142411_add_taggings_counter_cache_to_tags.acts_as_taggable_on_engine.rb
db/migrate/20160526142412_add_missing_taggable_index.acts_as_taggable_on_engine.rb
db/migrate/20160526142413_change_collation_for_tag_names.acts_as_taggable_on_engine.rb
db/schema.rb

!!!!!!!!!!!!!!!!!! ---------- This is a prototype ---- DO NOT MERGE ------- !!!!!!!!!!!!!!!!!!!!
@iAmNathanJ 
messing with stuff ... 
we may be able to use ruby's .parameterize.underscore to replace the space with underscore.
I might of messed up something cause I just forced pushed my changes.

Acts as taggable

---

Gemfile.lock
app/assets/javascripts/00-base.js
app/assets/javascripts/events.js
app/assets/stylesheets/base/_global.scss
app/assets/stylesheets/styles/_event-filters.scss
app/controllers/events_controller.rb
app/views/events/_event_card.html.erb
app/views/events/_filters.html.erb
db/schema.rb

This is the first iteration of the tagging system.

Acts as taggable / js filters

---

app/assets/stylesheets/styles/_event-filters.scss
app/assets/stylesheets/styles/_events.scss
app/assets/stylesheets/styles/_header.scss

@catheraaine @BC3209 @boomingbrake 
closes #125

Iss 125 mvp ui

---

app/controllers/events_controller.rb
app/views/events/_event_card.html.erb

I did it guys!!!
@iAmNathanJ @catheraaine @BC3209

Add new format respond to type for png to return logo of given event

---

app/controllers/events_controller.rb
app/views/events/_event_card.html.erb

tags are now armed and dangerous
@iAmNathanJ @catheraaine @BC3209

Tags need bullets

---

app/controllers/events_controller.rb
app/models/day.rb
app/models/frequency.rb
app/models/tag.rb
app/models/time.rb
app/models/topic.rb
app/views/events/_filters.html.erb

@iAmNathanJ   I DID IT!!!!!!!!! 
Filter state is solid... next step the cards.

Add new tag object to set state of ui

---

Gemfile
Gemfile.lock
app/assets/javascripts/application.js
app/assets/javascripts/events-index.js
app/assets/javascripts/query-string.js
app/assets/javascripts/tag-manager.js
app/views/events/_filters.html.erb
config/routes.rb
spec/javascripts/support/jasmine.yml
spec/javascripts/tag-manager.spec.js

This adds jasmine test runner and tests.
Currently WIP.

Rework JS filters with testing

---

app/assets/javascripts/application.js
app/assets/javascripts/card-list.js
app/assets/javascripts/dom-extensions.js
app/assets/javascripts/dom-selector.js
app/assets/javascripts/events-index.js
app/assets/javascripts/params-parser.js
app/assets/javascripts/tag-manager.js
spec/javascripts/card-list.spec.js
spec/javascripts/support/jasmine.yml
spec/javascripts/tag-manager.spec.js
test/integration/integration_test.rb

History has been written. Pun heavily intended. 
@BC3209 @boomingbrake @catheraaine Can you all *please* try to break this? Need to check that the filter buttons and the event cards update properly through the browser history (forward and back). BREAK IT!

Add push and popstate goodies

---

app/assets/javascripts/events-index.js

I missed this one change. This fixes page state, on back and forth, once and for all.
@catheraaine can you double check this? I think it's done.......... for now!

JS: small fix

---

app/assets/javascripts/tag-manager.js
app/models/event.rb
app/models/tag.rb
app/views/events/_event_card.html.erb

Good to go!
@iAmNathanJ @BC3209 @catheraaine

Add URI encode to tag name for filtering

---

app/models/event.rb
app/models/tag.rb
app/views/events/_event_card.html.erb

testing and all the best things

Change callback on event model

---

app/assets/javascripts/events-index.js
app/assets/stylesheets/ie.scss
app/views/layouts/application.html.erb
config/initializers/assets.rb

ie fixes are coming!
@catheraaine we now have a single ie.scss file that  builds its own stylesheet. It only loads in ie 10 and older.
This should kick off the fixing party. Can one of you review please? @BC3209 
closes #169

Fix: Nav overlaps card

---

app/assets/stylesheets/base/_global.scss
app/assets/stylesheets/ie.scss
app/assets/stylesheets/styles/_events.scss
app/views/layouts/application.html.erb

This should be good to go. Somebody wanna double check and merge? @boomingbrake @catheraaine @BC3209 
Closes #179

Fix: Text wrapping issue in ie 9/10

---

app/assets/stylesheets/base/_global.scss
app/views/about/index.html
app/views/events/_filters.html.erb
app/views/events/index.html.erb
app/views/events/show.html.erb
app/views/layouts/_header.html
app/views/layouts/application.html.erb

- About
- Single Card
- Filters Bar
closes #198

Feat: Add Copyright to pages

---

app/views/events/_event_card.html.erb
app/views/events/_location_icon.html.erb

:bug: Fix: Move <div> outside <ul> on Event Card

---

app/views/layouts/_header.html

@catheraaine @BC3209 @boomingbrake 
closes #205

Fix: Update homepage short description

---

app/assets/stylesheets/styles/_events.scss

@boomingbrake @catheraaine @BC3209 
It's big. It's centered. :)
closes #208

Fix: Make single card page full width

---

app/assets/stylesheets/base/_print.scss
app/assets/stylesheets/main.scss

@BC3209 @boomingbrake @catheraaine 
This ought to do it.
closes #203

Feat: Add print styles

---

app/assets/stylesheets/base/_global.scss
app/assets/stylesheets/main.scss
app/assets/stylesheets/styles/_about.scss
app/views/about/index.html

- I just made up some styles; will correct to "real version" later.

Feat: About Page

---

app/views/events/_event_card.html.erb
app/views/events/_filters.html.erb
app/views/events/index.html.erb
app/views/events/show.html.erb
app/views/layouts/_header.html

@iAmNathanJ @catheraaine @BC3209

Add roles to HTML5 elements

---

app/views/events/_filters.html.erb

HTML validation is clean up
@BC3209 @catheraaine @iAmNathanJ

Change filter id's to user tag.data_tag

---

app/views/layouts/_header.html
app/views/layouts/application.html.erb

- Header
- Title
- Submit email (x2)

Chore: Change "Lamppost" to "Lamp Post"

---

app/assets/stylesheets/base/_global.scss
app/views/events/_filters.html.erb
app/views/events/index.html.erb

@catheraaine @boomingbrake @BC3209

Fix: Move footer to bottom of main page

---

app/assets/stylesheets/styles/_logo.scss
app/views/events/_event_card.html.erb
app/views/events/index.html.erb
app/views/layouts/_header.html

BEEP BOOP BEEP
@BC3209 @catheraaine @iAmNathanJ

Add h1 to logo and put filter in nav element'

---

app/controllers/events_controller.rb
config/environments/production.rb

@catheraaine @BC3209 @boomingbrake this should be ready.

Caching fixes

---

app/assets/stylesheets/base/_global.scss
app/assets/stylesheets/styles/_events.scss
app/views/about/index.html
app/views/events/index.html.erb
app/views/events/show.html.erb

@catheraaine I think this should do it.

Fix: Footer alignment on all pages

---

README.md
app/assets/stylesheets/base/_global.scss
app/assets/stylesheets/styles/_event-filters.scss
app/views/events/_event_card.html.erb

Fix: Capitalize Filter Tags

---

app/views/about/index.html

@iAmNathanJ if you would be so kind...

Chore: Update repo link in 'About'

---

app/views/layouts/application.html.erb

Fix: Remove hard coded analytics key

---

README.md

@BC3209 @boomingbrake @catheraaine Wanna check this for format and spelling? More docs! 😄

Feat: Update README with analytics and rails admin stuff

---

app/assets/stylesheets/base/_variables.scss
app/assets/stylesheets/styles/_header.scss
app/views/layouts/application.html.erb

This is a preliminary fix for @marshallNorman re: #240
@catheraaine Could you review please? I think this should be merged, and then I'll come back with a more complete fix. Thanks!!

Fix Menu Layout

---

app/assets/stylesheets/styles/_events.scss
db/schema.rb

- Remove grey margins on stacked card
- Align text with divider on stacked card
closes #156, #241

Fix: Adjust padding and margin on card.

---

app/assets/stylesheets/styles/_events.scss

- on full sidebar stacked card view

Fix: Card Right Margin

---

app/assets/javascripts/events-index.js
app/assets/stylesheets/base/_global.scss
app/assets/stylesheets/styles/_event-filters.scss
app/assets/stylesheets/styles/_events.scss
app/assets/stylesheets/styles/_header.scss
app/assets/stylesheets/styles/_side-bar.scss

@BC3209 @catheraaine @boomingbrake 
This adds some polish to the filtering UI and fixes a couple minor annoyances.

Ux features

---

app/assets/stylesheets/styles/_event-filters.scss
app/models/tag.rb
app/views/events/_event_card.html.erb
config/application.rb

@iAmNathanJ @catheraaine @BC3209 
Now the backend gives you the proper cased tag/filter names, so removed css style

Add titleize to tag name

---

app/assets/stylesheets/base/_global.scss
app/models/event.rb
app/views/events/_event_card.html.erb

Need to test the production data via the review app.
This will still need styles applied @catheraaine

Feat: Make event addresses link to google maps

---

app/assets/stylesheets/base/_global.scss
app/views/about/index.html.erb
app/views/events/index.html.erb
app/views/events/show.html.erb
app/views/layouts/_footer.html.erb
db/schema.rb

- Plus a link!
@iAmNathanJ @BC3209 @boomingbrake 
closes #258

Feat: Add Footer Partial with updated text

---

app/controllers/events_controller.rb
app/models/tag.rb

@iAmNathanJ @BC3209 @catheraaine 
not sure what happened first time, but lets try this again.

Add method to order day filters

---

app/views/layouts/_header.html

Update submit email

---

app/assets/stylesheets/base/_global.scss
app/assets/stylesheets/styles/_events.scss
app/views/events/_event_card.html.erb
db/schema.rb

@marshallNorman Wanna check this? Let me know if anything looks wrong. I'd like to merge this and then work with @catheraaine on the double card layout. Cool?

Layout refinements

---

app/controllers/events_controller.rb
app/models/event.rb
db/migrate/20160622160617_add_expire_to_events.rb
db/schema.rb

@iAmNathanJ @catheraaine @BC3209 
I DID IT

Event expiration

---

app/views/layouts/_header.html
app/views/layouts/application.html.erb

- Add data in the meta for social sharing.

Feat: Open Graph

---

app/views/about/index.html.erb

@iAmNathanJ @catheraaine @BC3209

Add j to jump

---

app/views/events/index.rss.builder

@BC3209 I've filled out the RSS view to show all of the event info. Wanna give it a look?

RSS Additions

---

DEVELOPMENT.md
README.md
app.json
app/views/about/_about_content.html.erb

Lots of changes here. @catheraaine I opened #269 regarding some of the challenges here. 
I would love some feedback and help if you're able.

Docs upgrade

---

DEVELOPMENT.md
README.md
app.json
app/assets/stylesheets/styles/_about.scss
app/views/about/_about_content.html.erb
app/views/layouts/_header.html.erb

This adds the basic info anyone needs to setup their own lamppost and make it their own. More could be added, but hopefully this is a good start.
@catheraaine

Docs intermediate changes

---

README.md
app/assets/javascripts/events-show.js
app/assets/stylesheets/base/_global.scss
app/assets/stylesheets/base/_theme.scss
app/assets/stylesheets/base/_variables.scss
app/assets/stylesheets/styles/_event-filters.scss
app/assets/stylesheets/styles/_forms.scss
app/assets/stylesheets/styles/_header.scss
app/assets/stylesheets/styles/_logo.scss
app/assets/stylesheets/styles/_side-bar.scss

Feat: Add Theme options

---

app/assets/stylesheets/base/_theme.scss
app/assets/stylesheets/styles/_header.scss

@iAmNathanJ this is a tiny change

Fix: About/Submit Light theme hover color

---

DEVELOPMENT.md
Gemfile
Gemfile.lock
config/database.yml

@iAmNathanJ @catheraaine @BC3209 
if you want to dump your current db follow link below, you'll be using the "taps" command, and obviously switch the postgresql to sqlite3
http://stackoverflow.com/questions/6710654/change-from-sqlite-to-postgresql-in-a-fresh-rails-project

Change dev/test db to use sqlite

---

app/assets/stylesheets/main.scss
app/assets/stylesheets/styles/_empty-state.scss
app/views/events/_empty_state.html.erb
app/views/events/_event_list.html.erb

I added the empty state for the event listings and tweaked @catheraaine styling just a wee bit
@iAmNathanJ 
@boomingbrake

Add empty state to event list

---

.gitignore
app/assets/javascripts/events-index.js
app/assets/stylesheets/base/_mixins.scss
app/assets/stylesheets/styles/#_events.scss#
app/assets/stylesheets/styles/.#_events.scss
app/views/layouts/application.html.erb
db/schema.rb

@boomingbrake @BC3209 Can someone check that the review app doesn't have a loading error in the console. Then we'll need to merge and actually make sure the production app is getting the font.

Font fallback

---

app/controllers/application_controller.rb

@BC3209 Not sure if this will work...

Feat: Redirect www to https://
